// DATA FETCHING
const CHANGE_URL_SUCCESS = 'CHANGE_URL_SUCCESS';
const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';

// DARK MODE / LIGHT MODE
const COLOR_THEME_CHANGE = 'COLOR_THEME_CHANGE';

export {
  CHANGE_URL_SUCCESS,
  COLOR_THEME_CHANGE,
  FETCH_DATA_SUCCESS
}