// DATA FETCHING
const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';

// DARK MODE / LIGHT MODE
const COLOR_THEME_CHANGE = 'COLOR_THEME_CHANGE';

export {
  COLOR_THEME_CHANGE,
  FETCH_DATA_SUCCESS
}