// LOGS CHANGES
const LOG_BPM = 'LOG_BPM';
const LOG_CURRENT_TRACK = 'LOG_CURRENT_TRACK';
const LOG_KILL_ALL_TRACK = 'LOG_KILL_ALL_TRACK';
const LOG_SAVE_STATE = 'LOG_SAVE_STATE';
const LOG_STROBE_SPEED = 'LOG_STROBE_SPEED';
const LOG_TRACK = 'LOG_TRACK';

// DATA FETCHING
const CHANGE_URL_SUCCESS = 'CHANGE_URL_SUCCESS';
const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';

// DARK MODE / LIGHT MODE
const COLOR_THEME_CHANGE = 'COLOR_THEME_CHANGE';

export {
  CHANGE_URL_SUCCESS,
  COLOR_THEME_CHANGE,
  FETCH_DATA_SUCCESS,
  LOG_BPM,
  LOG_CURRENT_TRACK,
  LOG_KILL_ALL_TRACK,
  LOG_SAVE_STATE,
  LOG_STROBE_SPEED,
  LOG_TRACK
}